### ISSUE TITLE
Problem on tt2406566

### ISSUE THREAD

**Issue by JDommi** [tardezyx/tar.IMDbScraper#3]
Hi!

On the movie "Atomic Blonde" (tt2406566) there seems to be an error.
On the Release Dates the exporter produces an error:
"Nullable object must have a value"

By the way I have included the XMM 10 release as it is working on any movie - except for the above mentioned one.
https://www.mediafire.com/file/yimrwdgr3raw9zv/XMM-Release%2521.rar/file

**Comment by tardezyx** [comment]
Fixed in [v1.3.1](https://github.com/tardezyx/tar.IMDbScraper/releases/tag/1.3.1).
